package com.rao.playground.swing.transitions;

import com.sun.java.swing.plaf.windows.WindowsLookAndFeel;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 */
public class RichUIComponentTester {

  private JPanel mainPanel;
  private JButton launchTransitionPanelButton;
  private JButton launchWarpPanelButton;

  private static final String TITLE_PREFIX = "Java Swing Rich UI Component Tester";

  public RichUIComponentTester() {

    launchTransitionPanelButton.addActionListener(new ActionListener() {
      public void actionPerformed(ActionEvent e) {
        TransitionPanelTester flipPanelTester = new TransitionPanelTester();
        JFrame frame = new JFrame(TITLE_PREFIX + "Transition Panel");
        frame.setContentPane(flipPanelTester.getMainPanel());
        frame.pack();
        frame.setVisible(true);
      }
    });

//    launchWarpPanelButton.addActionListener(new ActionListener() {
//      public void actionPerformed(ActionEvent e) {
//        WarpTester warpPanelTester = new WarpTester();
//        JFrame frame = new JFrame(TITLE_PREFIX + "Warp Effect");
//        frame.setContentPane(warpPanelTester.getMainPanel());
//        frame.pack();
//        frame.setVisible(true);
//      }
//    });

  }

  public JPanel getMainPanel() {
    return mainPanel;
  }

  public static void main(String[] args) {

    try {
      UIManager.setLookAndFeel(new WindowsLookAndFeel());
    } catch (UnsupportedLookAndFeelException e) {
      e.printStackTrace();
    }

    SwingUtilities.invokeLater(new Runnable() {
      public void run() {
        RichUIComponentTester richUIComponentTesterPanel = new RichUIComponentTester();
        JFrame frame = new JFrame("Java Swing Rich UI Demo Launcher");
        frame.setContentPane(richUIComponentTesterPanel.getMainPanel());
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.setBounds(100, 100, 400, 500);
        frame.setVisible(true);
      }
    });

  }

  {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
    $$$setupUI$$$();
  }

  /**
   * Method generated by IntelliJ IDEA GUI Designer
   * >>> IMPORTANT!! <<<
   * DO NOT edit this method OR call it in your code!
   *
   * @noinspection ALL
   */
  private void $$$setupUI$$$() {
    mainPanel = new JPanel();
    mainPanel.setLayout(new GridBagLayout());
    launchTransitionPanelButton = new JButton();
    launchTransitionPanelButton.setText("Test Transition Panel");
    GridBagConstraints gbc;
    gbc = new GridBagConstraints();
    gbc.gridx = 0;
    gbc.gridy = 0;
    gbc.weightx = 1.0;
    gbc.fill = GridBagConstraints.HORIZONTAL;
    gbc.insets = new Insets(12, 12, 12, 12);
    mainPanel.add(launchTransitionPanelButton, gbc);
    launchWarpPanelButton = new JButton();
    launchWarpPanelButton.setText("Launch Warp Demo");
    gbc = new GridBagConstraints();
    gbc.gridx = 0;
    gbc.gridy = 1;
    gbc.weightx = 1.0;
    gbc.fill = GridBagConstraints.HORIZONTAL;
    gbc.insets = new Insets(12, 12, 12, 12);
    mainPanel.add(launchWarpPanelButton, gbc);
  }

  /**
   * @noinspection ALL
   */
  public JComponent $$$getRootComponent$$$() {
    return mainPanel;
  }
}
